apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: guestbook-ui
  annotations:
    kubernetes.io/ingress.class: "nginx-public"
spec:
  rules:
  - host: guestbook.example.com
    http:
      paths:
      - backend:
          serviceName: guestbook-ui
          servicePort: 80
